baseURL = "https://andrebossard.com/"
languageCode = "en-us"
title = "andrebossard.com"
theme = "andrebossard"
googleAnalytics = "UA-578294-7"
[params]
    description = "Andre Bossard 2020"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.main]]
  name = "Github"
  url = "https://github.com/abossard/"

[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/abossard/"

