# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ABOSSARD_IO_TOKEN }}
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: abossard/abossard.github.io
        token: ${{ secrets.ABOSSARD_IO_TOKEN }}  
        path: public
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        extended: true
    - name: Run Hugo
      run: hugo --minify --verbose -d public
    - name: Github Pages 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ABOSSARD_IO_TOKEN }}
        BRANCH: master
        FOLDER: public
        REPOSITORY_NAME: abossard/abossard.github.io
